# Generated by Django 4.2.11 on 2024-03-21 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, default='https://marketplace.canva.com/dmwQE/MAFo9ddmwQE/1/tl/canva-MAFo9ddmwQE.png', max_length=128, null=True)),
                ('router', models.CharField(default=None, max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('source_file', models.CharField(blank=True, max_length=128, null=True, verbose_name='任务源文件')),
                ('res_file', models.CharField(blank=True, max_length=128, null=True, verbose_name='任务结果文件')),
                ('task_status', models.IntegerField(choices=[(1, '等待中'), (2, '正在处理'), (3, '等待核对'), (4, '处理完成'), (5, '处理失败')], default=1, verbose_name='任务状态')),
                ('task_args', models.CharField(blank=True, max_length=2048, null=True, verbose_name='任务参数')),
                ('task_processing_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='任务处理ID')),
                ('task_msg', models.TextField(blank=True, null=True, verbose_name='任务当前信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('start_processing_time', models.DateTimeField(blank=True, null=True, verbose_name='开始处理时间')),
                ('end_processing_time', models.DateTimeField(blank=True, null=True, verbose_name='结束处理时间')),
                ('task_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tasks.function')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务创建用户')),
            ],
        ),
    ]
