# Generated by Django 4.2.11 on 2024-03-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='original_filename',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='原文件名'),
        ),
    ]
