# Generated by Django 4.2.11 on 2024-03-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.IntegerField(choices=[(1, '等待中'), (2, '正在处理'), (3, '处理完成'), (4, '处理失败')], default=1, verbose_name='任务状态'),
        ),
    ]
