# Generated by Django 4.2.11 on 2024-03-17 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=128)),
                ('file_path', models.CharField(blank=True, max_length=128, null=True)),
                ('file_url', models.CharField(blank=True, max_length=128, null=True)),
                ('file_type', models.IntegerField(choices=[(1, 'video'), (2, 'audio'), (3, 'image')])),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
