# Generated by Django 4.2.11 on 2024-03-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='delete_time',
        ),
        migrations.RemoveField(
            model_name='file',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='file',
            name='file_source',
            field=models.IntegerField(choices=[(1, '用户上传'), (2, '任务生成')], default=1),
        ),
        migrations.AddField(
            model_name='file',
            name='last_use_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
