# Generated by Django 4.2.11 on 2024-03-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_file_delete_time_remove_file_is_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='save_name',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
